# Generated by Django 3.2.16 on 2023-09-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertinfo',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='expertinfo',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='expertinfo',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
