# Generated by Django 3.2.16 on 2023-09-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0003_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertinfo',
            name='position',
            field=models.CharField(choices=[('PROG', 'Преподаватель по программированию'), ('ROBO', 'Преподаватель по робототехнике')], default=None, max_length=4),
        ),
    ]
