# Generated by Django 3.2.16 on 2023-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0005_auto_20230918_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experiens',
        ),
        migrations.AddField(
            model_name='expertinfo',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expertinfo',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expertinfo',
            name='study_facult',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expertinfo',
            name='study_form',
            field=models.CharField(blank=True, choices=[('INTERN', 'Очная'), ('DISTAN', 'Заочная')], default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='expertinfo',
            name='study_place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expertinfo',
            name='study_spec',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
