# Generated by Django 3.2.16 on 2023-09-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0006_auto_20230918_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpertInfo',
            new_name='TeachInfo',
        ),
    ]
