# Generated by Django 3.2.16 on 2023-09-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0007_rename_expertinfo_teachinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
