# Generated by Django 3.2.16 on 2023-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0008_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinfo',
            name='photo',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя участника'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Дата окончания обучения'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='position',
            field=models.CharField(choices=[('PROG', 'Преподаватель по программированию'), ('ROBO', 'Преподаватель по робототехнике')], default=None, max_length=4, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='study_facult',
            field=models.CharField(max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='study_form',
            field=models.CharField(blank=True, choices=[('INTERN', 'Очная'), ('DISTAN', 'Заочная')], default=None, max_length=6, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='study_place',
            field=models.TextField(null=True, verbose_name='Место обучения'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='study_spec',
            field=models.CharField(max_length=100, null=True, verbose_name='Специальность'),
        ),
    ]
