# Generated by Django 3.2.16 on 2023-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0009_auto_20230920_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachinfo',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='study_facult',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='study_place',
            field=models.TextField(blank=True, null=True, verbose_name='Место обучения'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='study_spec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специальность'),
        ),
    ]
