# Generated by Django 3.2.16 on 2023-09-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0011_auto_20230920_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='Название пакета')),
                ('price', models.IntegerField(verbose_name='Цена пакета')),
                ('descript', models.CharField(max_length=100, verbose_name='Описание')),
            ],
        ),
    ]
