# Generated by Django 3.2.16 on 2023-09-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0012_packagesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesinfo',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Название пакета'),
        ),
    ]
