# Generated by Django 3.2.16 on 2023-09-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0013_alter_packagesinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена пакета'),
        ),
    ]
