# Generated by Django 3.2.16 on 2023-10-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0018_auto_20231006_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachinfo',
            name='date_end',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата окончания обучения'),
        ),
        migrations.AlterField(
            model_name='teachinfo',
            name='date_start',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата начала обучения'),
        ),
    ]
